### ISSUE TITLE
model‘s path error

### ISSUE THREAD

**Issue by zhywanna** [yilundu/nerflow#2]
![image](https://user-images.githubusercontent.com/47680024/148172546-29daa686-3171-4388-8eac-b37912cc021a.png)
Hi, could you please help me figure out? I just move alexnet-owt-7be5be79.pth to the requrie dir doesn't work.

**Comment by yilundu** [comment]
Hmm can you specify what you ran to get the above result? When I tried running the above code, it was able to download the model directly.
